"""add rate_car table

Revision ID: bb78ba5cd0e3
Revises: 0864ea2d8143
Create Date: 2022-03-25 08:18:12.645054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb78ba5cd0e3'
down_revision = '0864ea2d8143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('cars', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('cars', 'brand',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('cars', 'model',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('cars', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cars', 'model',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('cars', 'brand',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('cars', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('cars', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
