"""add genre table

Revision ID: bc3dff42ed26
Revises: bb78ba5cd0e3
Create Date: 2022-03-28 13:31:22.461244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3dff42ed26'
down_revision = 'bb78ba5cd0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('genre', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'genre_id')
    # ### end Alembic commands ###
